# Generated by Django 5.2 on 2025-11-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_doctor_pharmacy_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
