# Generated by Django 5.2 on 2025-11-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_location_tourplan_userlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='langitude',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='shared.district'),
        ),
        migrations.AlterField(
            model_name='location',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='shared.doctor'),
        ),
        migrations.AlterField(
            model_name='location',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='shared.pharmacy'),
        ),
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='shared.place'),
        ),
    ]
