# Generated by Django 5.2 on 2025-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_rename_langitude_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourplan',
            name='district',
        ),
        migrations.AddField(
            model_name='tourplan',
            name='location_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='place_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
