# Generated by Django 5.2 on 2025-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0009_remove_tourplan_district_tourplan_location_send_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
