# Generated by Django 5.2 on 2025-11-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0010_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
