# Generated by Django 5.2 on 2025-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0011_tourplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='extra_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
