# Generated by Django 5.2 on 2025-12-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0014_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('PROBLEM', 'muammo'), ('HELP', 'yordam')], default='PROBLEM', max_length=8),
        ),
    ]
