# Generated by Django 5.2 on 2025-12-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0015_support_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='shared.doctor'),
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plan',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plan',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='shared.pharmacy'),
        ),
    ]
