# Generated by Django 5.2 on 2025-12-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0016_plan_comment_plan_doctor_plan_extra_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports', to='shared.district'),
        ),
    ]
