# Generated by Django 5.2 on 2025-12-11 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0017_alter_support_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('user', 'name')},
        ),
    ]
