# Generated by Django 5.2 on 2025-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
