# Generated by Django 5.2 on 2025-12-17 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permissiongroup_permissionmodul_permissionaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_action',
            field=models.ManyToManyField(related_name='permission_actions', to='accounts.permissionaction'),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_groups',
            field=models.ManyToManyField(related_name='permission_groups', to='accounts.permissiongroup'),
        ),
        migrations.CreateModel(
            name='PermissionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.permissiongroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permission_modules',
            field=models.ManyToManyField(related_name='permission_modules', to='accounts.permissionmodule'),
        ),
        migrations.AlterField(
            model_name='permissionaction',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.permissionmodule'),
        ),
        migrations.DeleteModel(
            name='PermissionModul',
        ),
    ]
