# Generated by Django 5.2 on 2025-12-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_permission_action_role_permission_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permission_action',
            new_name='permission_actions',
        ),
        migrations.RemoveField(
            model_name='permissionaction',
            name='modul',
        ),
        migrations.AddField(
            model_name='permissionaction',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accounts.permissionmodule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissionmodule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='accounts.permissiongroup'),
        ),
    ]
