# Generated by Django 5.2 on 2025-11-27 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shared', '0010_factory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='order',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shared.factory'),
        ),
    ]
