# Generated by Django 5.2 on 2025-11-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_pharmacy_order_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overdue_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
