# Generated by Django 5.2 on 2025-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_overdue_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders/files/'),
        ),
    ]
