# Generated by Django 5.2 on 2025-11-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid_until',
        ),
    ]
